In [1]:
import pandas as pd

In [2]:
df= pd.read_csv("../resources/data1.csv")

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  93 non-null     int64
 1   Sr No       93 non-null     int64
 2   Paper Name  93 non-null     str
 3   Paper Code  93 non-null     str
 4   GEN         93 non-null     float64
 5   OBC         93 non-null     float64
 6   SC/ST       93 non-null     float64
 7   Year        93 non-null     int64
dtypes: float64(3), int64(3), str(2)
memory usage: 5.9 KB

In [4]:
df.shape

(93, 8)

In [5]:
df.describe()

       Unnamed: 0      Sr No        GEN        OBC      SC/ST         Year
count   93.000000  93.000000  93.000000  93.000000  93.000000    93.000000
mean    46.000000  47.000000  32.317957  29.084946  21.509032  2018.311828
std     26.990739  26.990739   6.779166   6.069802   4.525539     1.510676
min      0.000000   1.000000  25.000000  22.500000  16.600000  2015.000000
25%     23.000000  24.000000  26.400000  24.000000  17.500000  2018.000000
50%     46.000000  47.000000  31.700000  28.500000  21.000000  2019.000000
75%     69.000000  70.000000  36.600000  32.900000  24.400000  2020.000000
max     92.000000  93.000000  53.500000  48.100000  35.700000  2020.000000

In [6]:
df["Paper Code"]

0     XL
1     CE
2     EE
3     CS
4     ME
      ..
88    EE
89    EC
90    CS
91    IN
92    PI
Name: Paper Code, Length: 93, dtype: str

In [12]:
df[df["Year"] == 2019]["GEN"].mean()

np.float64(34.6)

In [13]:
df[df["Year"] == 2019]["OBC"].max()

np.float64(48.1)

In [15]:
df.groupby("Year")["Paper Code"].count()

Year
2015     7
2016     7
2017     8
2018    23
2019    24
2020    24
Name: Paper Code, dtype: int64

In [16]:
df.groupby("Paper Code")["GEN"].mean().sort_values(ascending=False)

Paper Code
MT    47.666667
PE    43.166667
EY    42.866667
AR    39.900000
GG    38.433333
CH    38.150000
TF    36.466667
MN    36.400000
BT    33.350000
ME    33.000000
XL    32.766667
IN    32.130000
AE    31.700000
PI    30.804000
PH    30.466667
EE    29.566667
ST    28.750000
XE    28.066667
CY    28.033333
CE    27.783333
AG    26.533333
MA    26.466667
CS    26.333333
EC    25.916667
BM    25.000000
Name: GEN, dtype: float64

In [19]:
f = (df["Paper Code"] == "PE") & (df["Year"] > 2018)
df[f]

,Unnamed: 0,Sr No,Paper Name,Paper Code,GEN,OBC,SC/ST,Year
5,5,6,Petroleum Engineering,PE,39.8,35.8,26.5,2020
29,29,30,Petroleum Engineering,PE,49.9,44.9,33.3,2019

In [21]:
f = (df["Paper Code"] == "PE")
df[f].iloc[0:2]

,Unnamed: 0,Sr No,Paper Name,Paper Code,GEN,OBC,SC/ST,Year
5,5,6,Petroleum Engineering,PE,39.8,35.8,26.5,2020
29,29,30,Petroleum Engineering,PE,49.9,44.9,33.3,2019

In [28]:
df[f].loc[20:]

,Unnamed: 0,Sr No,Paper Name,Paper Code,GEN,OBC,SC/ST,Year
29,29,30,Petroleum Engineering,PE,49.9,44.9,33.3,2019
65,65,66,Petroleum Engineering,PE,39.8,35.8,26.5,2018

In [30]:
df.value_counts("Paper Name")

Paper Name
Civil Engineering                              6
Electrical Engineering                         6
Mechanical Engineering                         6
Computer Science and Information Technology    5
Production and Industrial Engineering          5
Electronics and Communication Engineering      4
Chemical Engineering                           4
Biotechnology                                  4
Instrumentation Engineering                    4
Life Sciences                                  3
Petroleum Engineering                          3
Chemistry                                      3
Textile Engineering and Fibre Science          3
Aerospace Engineering                          3
Agricultural Engineering                       3
Architecture and Planning                      3
Ecology and Evolution                          3
Mathematics                                    3
Mining Engineering                             3
Metallurgical Engineering                      3
Physics                                        3
Statistics                                     2
Engineering Sciences                           2
Geology and Geophysics                         2
Engineering Sciences Minor                     1
Geology                                        1
Biomedical Engineering                         1
Electronics and Communication                  1
Computer Science & Information Technology      1
Electronics and Communication Engineering      1
Instrumentation Engineering                    1
Name: count, dtype: int64

In [31]:
df.groupby("Paper Name")["GEN"].mean().sort_values(ascending=False)

Paper Name
Metallurgical Engineering                      47.666667
Petroleum Engineering                          43.166667
Ecology and Evolution                          42.866667
Architecture and Planning                      39.900000
Geology and Geophysics                         38.450000
Geology                                        38.400000
Chemical Engineering                           38.150000
Textile Engineering and Fibre Science          36.466667
Mining Engineering                             36.400000
Biotechnology                                  33.350000
Mechanical Engineering                         33.000000
Life Sciences                                  32.766667
Instrumentation Engineering                    32.262500
Aerospace Engineering                          31.700000
Instrumentation Engineering                    31.600000
Production and Industrial Engineering          30.804000
Physics                                        30.466667
Electrical Engineering                         29.566667
Engineering Sciences                           29.100000
Statistics                                     28.750000
Chemistry                                      28.033333
Civil Engineering                              27.783333
Computer Science and Information Technology    26.600000
Agricultural Engineering                       26.533333
Mathematics                                    26.466667
Electronics and Communication Engineering      26.375000
Engineering Sciences Minor                     26.000000
Computer Science & Information Technology      25.000000
Biomedical Engineering                         25.000000
Electronics and Communication                  25.000000
Electronics and Communication Engineering      25.000000
Name: GEN, dtype: float64

In [36]:
f= {"GEN": "mean", "Paper Code": "count"}
df.groupby("Paper Name").agg(f)

                                                   GEN  Paper Code
Paper Name
Aerospace Engineering                        31.700000           3
Agricultural Engineering                     26.533333           3
Architecture and Planning                    39.900000           3
Biomedical Engineering                       25.000000           1
Biotechnology                                33.350000           4
Chemical Engineering                         38.150000           4
Chemistry                                    28.033333           3
Civil Engineering                            27.783333           6
Computer Science & Information Technology    25.000000           1
Computer Science and Information Technology  26.600000           5
Ecology and Evolution                        42.866667           3
Electrical Engineering                       29.566667           6
Electronics and Communication                25.000000           1
Electronics and Communication Engineering    26.375000           4
Electronics and Communication Engineering    25.000000           1
Engineering Sciences                         29.100000           2
Engineering Sciences Minor                   26.000000           1
Geology                                      38.400000           1
Geology and Geophysics                       38.450000           2
Instrumentation Engineering                  32.262500           4
Instrumentation Engineering                  31.600000           1
Life Sciences                                32.766667           3
Mathematics                                  26.466667           3
Mechanical Engineering                       33.000000           6
Metallurgical Engineering                    47.666667           3
Mining Engineering                           36.400000           3
Petroleum Engineering                        43.166667           3
Physics                                      30.466667           3
Production and Industrial Engineering        30.804000           5
Statistics                                   28.750000           2
Textile Engineering and Fibre Science        36.466667           3